// <auto-generated />
using System;
using DiDuDuaDi.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiDuDuaDi.API.Data.Migrations
{
    [DbContext(typeof(DiDuDuaDiDbContext))]
    [Migration("20260608084542_BaselineSchema")]
    partial class BaselineSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DiDuDuaDi.API.Data.AccountSchema", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<byte>("RoleId")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_accounts_email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("idx_accounts_role_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("uq_accounts_username");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.AudioPlayEventSchema", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("vi")
                        .HasColumnName("language_code");

                    b.Property<string>("PoiId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("poi_id");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("shop_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("tts")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("PoiId");

                    b.HasIndex("ShopId", "CreatedAt")
                        .HasDatabaseName("idx_audio_play_events_shop_id_created_at");

                    b.ToTable("audio_play_events", (string)null);
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.CashClaimCodeSchema", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("amount");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("claimed_at");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("issued_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("note");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("shop_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("issued")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_cash_claim_codes_code");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("idx_cash_claim_codes_shop_id");

                    b.ToTable("cash_claim_codes", (string)null);
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.ChatMessageSchema", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sender_role");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "CreatedAt")
                        .HasDatabaseName("idx_chat_messages_session_id_created_at");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.ChatSessionSchema", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("account_id");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("vi")
                        .HasColumnName("language_code");

                    b.Property<DateTime>("LastMessageAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("last_message_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("idx_chat_sessions_account_id");

                    b.ToTable("chat_sessions", (string)null);
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.MenuItemSchema", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_available");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("shop_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("idx_menu_items_shop_id");

                    b.HasIndex("ShopId", "IsAvailable")
                        .HasDatabaseName("idx_menu_items_shop_id_available");

                    b.ToTable("menu_items", (string)null);
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.OwnerUpgradeRequestSchema", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("activated_at");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address_line");

                    b.Property<string>("BusinessLicenseImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("business_license_image_url");

                    b.Property<string>("IdCardImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("id_card_image_url");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("longitude");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("note");

                    b.Property<DateTime?>("PaymentConfirmedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("payment_confirmed_at");

                    b.Property<string>("PaymentQrContent")
                        .HasColumnType("text")
                        .HasColumnName("payment_qr_content");

                    b.Property<string>("PaymentQrImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("payment_qr_image_url");

                    b.Property<string>("PaymentReferenceCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("payment_reference_code");

                    b.Property<DateTime?>("PaymentRequestedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("payment_requested_at");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("review_note");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedByAccountId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("reviewed_by_account_id");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("shop_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("submitted_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("UpgradeFeeAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("upgrade_fee_amount");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("idx_owner_upgrade_requests_account_id");

                    b.HasIndex("ReviewedByAccountId");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_owner_upgrade_requests_status");

                    b.ToTable("owner_upgrade_requests", (string)null);
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.PoiSchema", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("food")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DefaultLanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("vi")
                        .HasColumnName("default_language_code");

                    b.Property<string>("HeroImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("hero_image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_featured");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("longitude");

                    b.Property<string>("ShopId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("shop_id");

                    b.Property<int>("TriggerRadiusMeters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(35)
                        .HasColumnName("trigger_radius_meters");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("idx_pois_category");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_pois_active");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("idx_pois_shop_id");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("idx_pois_lat_lng");

                    b.ToTable("pois", (string)null);
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.PoiTranslationSchema", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("audio_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("language_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("PoiId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("poi_id");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("short_description");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("LanguageCode")
                        .HasDatabaseName("idx_poi_translations_language_code");

                    b.HasIndex("PoiId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("uq_poi_translations_poi_lang");

                    b.ToTable("poi_translations", (string)null);
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.RoleSchema", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("display_name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_roles_code");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.ShopSchema", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address_line");

                    b.Property<string>("ApprovedIntro")
                        .HasColumnType("text")
                        .HasColumnName("approved_intro");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("IntroReviewNote")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("intro_review_note");

                    b.Property<string>("IntroReviewStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("approved")
                        .HasColumnName("intro_review_status");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsTemporarilyClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_temporarily_closed");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("opening_hours");

                    b.Property<string>("OwnerAccountId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("owner_account_id");

                    b.Property<string>("PendingIntro")
                        .HasColumnType("text")
                        .HasColumnName("pending_intro");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId")
                        .HasDatabaseName("idx_shops_owner_account_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uq_shops_slug");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("idx_shops_lat_lng");

                    b.ToTable("shops", (string)null);
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.ShopVisitEventSchema", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("vi")
                        .HasColumnName("language_code");

                    b.Property<string>("PoiId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("poi_id");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("shop_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("map")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("PoiId");

                    b.HasIndex("ShopId", "CreatedAt")
                        .HasDatabaseName("idx_shop_visit_events_shop_id_created_at");

                    b.ToTable("shop_visit_events", (string)null);
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.TourPoiSchema", b =>
                {
                    b.Property<string>("TourId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("tour_id");

                    b.Property<string>("PoiId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("poi_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<int>("StopMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("stop_minutes");

                    b.HasKey("TourId", "PoiId");

                    b.HasIndex("PoiId");

                    b.HasIndex("TourId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("uq_tour_pois_tour_sort");

                    b.ToTable("tour_pois", (string)null);
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.TourSchema", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("cover_image_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedByAccountId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("EstimatedDurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("estimated_duration_minutes");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_tours_code");

                    b.HasIndex("CreatedByAccountId")
                        .HasDatabaseName("idx_tours_created_by_account_id");

                    b.ToTable("tours", (string)null);
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.UserFavoriteSchema", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("account_id");

                    b.Property<string>("PoiId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("poi_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("AccountId", "PoiId");

                    b.HasIndex("PoiId");

                    b.ToTable("user_favorites", (string)null);
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.VisitorActivityEventSchema", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Page")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("map")
                        .HasColumnName("page");

                    b.Property<string>("SessionKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("session_key");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("map")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_visitor_activity_events_created_at");

                    b.HasIndex("SessionKey", "CreatedAt")
                        .HasDatabaseName("idx_visitor_activity_events_session_created_at");

                    b.ToTable("visitor_activity_events", (string)null);
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.AccountSchema", b =>
                {
                    b.HasOne("DiDuDuaDi.API.Data.RoleSchema", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_role_id");
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.AudioPlayEventSchema", b =>
                {
                    b.HasOne("DiDuDuaDi.API.Data.PoiSchema", null)
                        .WithMany()
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audio_play_events_poi_id");

                    b.HasOne("DiDuDuaDi.API.Data.ShopSchema", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audio_play_events_shop_id");
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.CashClaimCodeSchema", b =>
                {
                    b.HasOne("DiDuDuaDi.API.Data.ShopSchema", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cash_claim_codes_shop_id");
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.ChatMessageSchema", b =>
                {
                    b.HasOne("DiDuDuaDi.API.Data.ChatSessionSchema", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_session_id");
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.ChatSessionSchema", b =>
                {
                    b.HasOne("DiDuDuaDi.API.Data.AccountSchema", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_chat_sessions_account_id");
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.MenuItemSchema", b =>
                {
                    b.HasOne("DiDuDuaDi.API.Data.ShopSchema", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_menu_items_shop_id");
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.OwnerUpgradeRequestSchema", b =>
                {
                    b.HasOne("DiDuDuaDi.API.Data.AccountSchema", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_owner_upgrade_requests_account_id");

                    b.HasOne("DiDuDuaDi.API.Data.AccountSchema", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByAccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_owner_upgrade_requests_reviewer");
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.PoiSchema", b =>
                {
                    b.HasOne("DiDuDuaDi.API.Data.ShopSchema", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pois_shop_id");
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.PoiTranslationSchema", b =>
                {
                    b.HasOne("DiDuDuaDi.API.Data.PoiSchema", null)
                        .WithMany()
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_poi_translations_poi_id");
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.ShopSchema", b =>
                {
                    b.HasOne("DiDuDuaDi.API.Data.AccountSchema", null)
                        .WithMany()
                        .HasForeignKey("OwnerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shops_owner_account_id");
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.ShopVisitEventSchema", b =>
                {
                    b.HasOne("DiDuDuaDi.API.Data.PoiSchema", null)
                        .WithMany()
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shop_visit_events_poi_id");

                    b.HasOne("DiDuDuaDi.API.Data.ShopSchema", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shop_visit_events_shop_id");
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.TourPoiSchema", b =>
                {
                    b.HasOne("DiDuDuaDi.API.Data.PoiSchema", null)
                        .WithMany()
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tour_pois_poi_id");

                    b.HasOne("DiDuDuaDi.API.Data.TourSchema", null)
                        .WithMany()
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tour_pois_tour_id");
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.TourSchema", b =>
                {
                    b.HasOne("DiDuDuaDi.API.Data.AccountSchema", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tours_created_by_account_id");
                });

            modelBuilder.Entity("DiDuDuaDi.API.Data.UserFavoriteSchema", b =>
                {
                    b.HasOne("DiDuDuaDi.API.Data.AccountSchema", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_favorites_account_id");

                    b.HasOne("DiDuDuaDi.API.Data.PoiSchema", null)
                        .WithMany()
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_favorites_poi_id");
                });
#pragma warning restore 612, 618
        }
    }
}
